version: '3.8'

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - jproxy-payment1
      - jproxy-payment2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 44M
    networks:
      - my-backend-net

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning --maxmemory 50mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
    networks:
      - my-backend-net

  jproxy-payment1:
    image: jproxy-payment:latest
    depends_on:
      - redis
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - INSTANCE_ID=1
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: 128M
    networks:
      - my-backend-net
      - payment-processor

  jproxy-payment2:
    image: jproxy-payment:latest
    depends_on:
      - redis
    ports:
      - "8081:8080"
    environment:
      - REDIS_HOST=redis
      - INSTANCE_ID=2
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: 128M
    networks:
      - my-backend-net
      - payment-processor

networks:
  my-backend-net:
    driver: bridge
  payment-processor:
    external: true